name: Compile with SourceMod

on:
  pull_request:
    branches: bhop-brethren
  push:
    branches: bhop-brethren

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Set environment variables
        run: echo SCRIPTS_PATH=$(pwd) >> $GITHUB_ENV
      - name: Setup SourcePawn Compiler ${{ matrix.SM_VERSION }}
        id: setup_sp
        uses: rumblefrog/setup-sp@master
        with:
          version: '1.12.x'

      - name: Compile plugins
        run: |
          mkdir -p ./addons/sourcemod/scripting/include/ripext
          mkdir -p ./addons/sourcemod/scripting/include/json
          mkdir -p ./addons/sourcemod/scripting/include/json/helpers
          
          curl -LJO "https://raw.githubusercontent.com/ErikMinekus/sm-ripext/main/pawn/scripting/include/{ripext.inc,ripext/http.inc,ripext/json.inc}"
          mv ripext.inc ./addons/sourcemod/scripting/include
          mv http.inc json.inc ./addons/sourcemod/scripting/include/ripext

          curl -LJO "https://raw.githubusercontent.com/clugg/sm-json/master/addons/sourcemod/scripting/include/{json.inc,json/array.inc,json/definitions.inc,json/object.inc,json/helpers/decode.inc,json/helpers/errors.inc,json/helpers/metastringmap.inc,json/helpers/string.inc,json/helpers/typedstringmap.inc,json/helpers/unicode.inc}"
          mv json.inc ./addons/sourcemod/scripting/include
          mv array.inc definitions.inc object.inc ./addons/sourcemod/scripting/include/json
          mv decode.inc errors.inc metastringmap.inc string.inc typedstringmap.inc unicode.inc ./addons/sourcemod/scripting/include/json/helpers

          for FILE in ./addons/sourcemod/scripting/*.sp;
          do
            echo -e "\nCompiling $file..."
            spcomp -w234 -O2 -v2 -i ./addons/sourcemod/scripting/include $FILE
          done
          echo "===OUT FILES==="
          ls
        working-directory: ${{ env.SCRIPTS_PATH }}

      - name: Changelog
        id: changelog
        uses: mindsers/changelog-reader-action@v2.0.0

      - name: Install zip
        uses: montudor/action-zip@v1

      - name: Zip output
        run: zip -qq -r release.zip *.smx
        working-directory: ${{ env.SCRIPTS_PATH }}

      - name: Create Release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ steps.setup_sp.outputs.plugin-version }}
          artifacts: "release.zip"
          body: ${{ steps.changelog.outputs.changes }}
          draft: false
          allowUpdates: true
          prerelease: false
          replacesArtifacts: true